services:
  notification:
    image: notification
    build:
      context: .
      dockerfile: src/FSPodiumNotificationService/FSPodiumNotificationService.Web/Dockerfile
    depends_on:
      - postgres
      - seq
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=minoddein.ezz@gmail.com
      - SMTP_PASSWORD=urlruiukmyuarruj
    ports:
      - "5004:80"
      - "8095:443"

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "notifications"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "345890"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-data: